[MicroTVM] fix compile error when the compiler implements char as unsigned (#12519)
When compiling tvm with micro on the compiler which implements char as unsigned(such as arm-linux-gcc), there is an error:
`src/runtime/crt/graph_executor/load_json.c:218:12: error: result of comparison of constant -1 with expression of type 'char' is always false [-Werror,-Wtautological-constant-out-of-range-compare]`
`    if (ch == EOF || ch == '\r' || ch == '\n') {`
The reason is because the implementation of char is undefined, so it's better to specify here that it is signed.