[HotFix] Fix python import (#13099)
* [HotFix] Fix python import

Tuning doesn't work after #12969.
It reports the following error:

```
ImportError: cannot import name 'get_const_float' from partially initialized module 'tvm.topi.utils' (most likely due to a circular import)
```

In this commit I moved import relay to a function which used in a test.
And it helps to fix this circular import

* Fix lint